import React,{useState} from 'react';
import seed from './academyCatalog.json';
import './academy.css';

export const catalog=seed.areas;
export function validTrack(t){return t&&typeof t.id==='string'&&/^[a-z0-9-]{3,48}$/.test(t.id)&&typeof t.title==='string'&&t.title.trim().length>2&&typeof t.areaId==='string'&&catalog.some(a=>a.id===t.areaId)&&Array.isArray(t.lessons)&&t.lessons.length>0&&t.lessons.every(l=>typeof l.id==='string'&&/^[a-z0-9-]{3,48}$/.test(l.id)&&typeof l.title==='string'&&typeof l.concept==='string'&&typeof l.question==='string'&&Array.isArray(l.choices)&&l.choices.length===3&&Number.isInteger(l.correct)&&l.correct>=0&&l.correct<3)&&(!t.challenges||Array.isArray(t.challenges)&&t.challenges.every(c=>typeof c.id==='string'&&typeof c.flag==='string'&&/^SCHOOL\{[a-z0-9_-]+\}$/.test(c.flag)))}
export function allAreas(packs=[]){return catalog.map(area=>({...area,tracks:[...area.tracks,...packs.filter(t=>t.areaId===area.id)]}));}
export function academyTotal(packs=[]){return allAreas(packs).flatMap(a=>a.tracks).reduce((n,t)=>n+t.lessons.length+(t.challenges?.length||0),0)}

export default function Academy({profile,packs=[],award,initialArea='all',onAiPath}){
  const [areaId,setAreaId]=useState(initialArea),[trackId,setTrackId]=useState(null),[lessonId,setLessonId]=useState(null),[answer,setAnswer]=useState(null),[flag,setFlag]=useState(''),[hint,setHint]=useState(false),[feedback,setFeedback]=useState('');
  const areas=allAreas(packs),area=areas.find(a=>a.id===areaId),track=area?.tracks.find(t=>t.id===trackId),lesson=track?.lessons.find(l=>l.id===lessonId),challenge=track?.challenges?.find(c=>c.id===lessonId),done=profile?.completed||{};
  function chooseArea(id){setAreaId(id);setTrackId(null);setLessonId(null);setFeedback('')}
  function chooseTrack(id){setTrackId(id);setLessonId(null);setFeedback('')}
  function chooseItem(id){setLessonId(id);setAnswer(null);setFlag('');setHint(false);setFeedback('')}
  function submitFlag(){if(!profile){setFeedback('ادخل باسمك من الرئيسية لحفظ تقدمك.');return}if(flag.trim()===challenge.flag){award(`academy:${challenge.id}`,challenge.points||40);setFeedback(`علم صحيح! +${done[`academy:${challenge.id}`]?0:challenge.points||40} XP`)}else setFeedback('العلم غير مطابق. اقرأ النص واستعن بالتلميح إذا احتجت.')}
  return <section className="academy"><header className="academy-heading"><span className="eyebrow">FUTURE LEARNING LAB / ACADEMY</span><h1>اختر عالمك. <em>وابنِ مهارتك.</em></h1><p>مسارات قصيرة، أنشطة للتحقق من الفهم، وتحديات تدريبية آمنة. تُحفظ الإنجازات على هذا الجهاز.</p></header>
  <div className="academy-tabs" role="tablist" aria-label="الأقسام"><button className={areaId==='all'?'selected':''} onClick={()=>chooseArea('all')}>كل الأقسام</button>{areas.map(a=><button key={a.id} className={areaId===a.id?'selected':''} onClick={()=>chooseArea(a.id)}>{a.icon} {a.title}</button>)}</div>
  {!area&&<div className="academy-worlds">{areas.map(a=><button key={a.id} className="academy-world glass" style={{'--area':a.accent}} onClick={()=>chooseArea(a.id)}><span className="world-icon">{a.icon}</span><small>عالم {a.id.toUpperCase()} · {a.tracks.length} مسارات</small><h2>{a.title}</h2><p>{a.description}</p><strong>استكشف المسارات ←</strong></button>)}</div>}
  {area&&!track&&<><div className="academy-section" style={{'--area':area.accent}}><span>{area.icon}</span><div><small>عالم {area.id.toUpperCase()}</small><h2>{area.title}</h2><p>{area.description}</p></div></div><div className="academy-tracks">{area.id==='ai'&&<button className="academy-track glass" onClick={onAiPath}><small>المسار الرئيسي · 12 درسًا</small><h3>من الفكرة إلى مساعد المدرسة الذكي</h3><p>المسار التطبيقي الحالي: أربع مراحل مترابطة تنتهي بمشروعك.</p><span>افتح المسار ←</span></button>}{area.tracks.map(t=><button key={t.id} className="academy-track glass" onClick={()=>chooseTrack(t.id)}><small>{t.level||'تمهيدي'} · {t.lessons.length} دروس · {t.challenges?.length||0} تحديات</small><h3>{t.title}</h3><p>{t.description}</p><span>ادخل المسار ←</span></button>)}</div></>}
  {track&&!lessonId&&<><button className="academy-back" onClick={()=>chooseTrack(null)}>→ كل مسارات {area.title}</button><div className="academy-section" style={{'--area':area.accent}}><span>{area.icon}</span><div><small>{track.level||'تمهيدي'} / {area.title}</small><h2>{track.title}</h2><p>{track.description}</p></div></div><h3 className="academy-subtitle">الدروس · افهم وطبّق</h3><div className="academy-items">{track.lessons.map((l,i)=><button className="academy-item glass" key={l.id} onClick={()=>chooseItem(l.id)}><i>{String(i+1).padStart(2,'0')}</i><div><small>{done[`academy:${l.id}`]?'مكتمل ✓':'درس تفاعلي · 20 XP'}</small><h3>{l.title}</h3></div><span>←</span></button>)}</div>{!!track.challenges?.length&&<><h3 className="academy-subtitle">التحديات · جرّب مهارتك</h3><div className="academy-items">{track.challenges.map(c=><button className="academy-item glass" key={c.id} onClick={()=>chooseItem(c.id)}><i>⚑</i><div><small>{c.category} · {done[`academy:${c.id}`]?'تم التقاط العلم ✓':`${c.points||40} XP`}</small><h3>{c.title}</h3></div><span>←</span></button>)}</div></>}</>}
  {lessonId&&<><button className="academy-back" onClick={()=>chooseItem(null)}>→ العودة إلى {track.title}</button><div className="academy-detail glass" style={{'--area':area.accent}}><span className="eyebrow">{challenge?'مختبر التقاط العلم':'درس تفاعلي'} / {track.title}</span><h2>{(lesson||challenge)?.title}</h2>{lesson?<><div className="academy-content"><h3>الفكرة</h3><p>{lesson.concept}</p><h3>مثال</h3><p>{lesson.example}</p><h3>تطبيقك</h3><p>{lesson.task}</p></div><div className="academy-check"><small>تحقق من فهمك</small><h3>{lesson.question}</h3>{lesson.choices.map((choice,i)=><button key={i} className={answer===i?(i===lesson.correct?'right':'incorrect'):''} onClick={()=>setAnswer(i)}>{choice}</button>)}{answer!==null&&<p className={answer===lesson.correct?'success':''}>{lesson.explain}</p>}{answer===lesson.correct&&<button className="academy-primary" disabled={!profile||!!done[`academy:${lesson.id}`]} onClick={()=>award(`academy:${lesson.id}`,20)}>{done[`academy:${lesson.id}`]?'مكتمل ✓':profile?'أكمل الدرس · +20 XP':'ادخل باسمك من الرئيسية لحفظ التقدم'}</button>}</div></>:<><p className="academy-prompt">{challenge.prompt}</p><label className="academy-flag">العلم <input dir="ltr" autoComplete="off" spellCheck="false" placeholder="SCHOOL{...}" value={flag} onChange={e=>setFlag(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submitFlag()}/></label><div className="academy-actions"><button onClick={()=>setHint(true)}>✦ تلميح</button><button className="academy-primary" onClick={submitFlag}>إرسال العلم</button></div>{hint&&<p className="academy-hint">{challenge.hint}</p>}{feedback&&<p role="status" className={feedback.startsWith('علم صحيح')?'success':''}>{feedback}{feedback.startsWith('علم صحيح')&&` · ${challenge.explain}`}</p>}</>}</div></>}
  </section>
}
