import React,{useEffect,useState} from 'react';
import {skills,diagnostics,qualifiers,score} from './competitionBank.js';
import './competition.css';

const duration=12*60*1000;
const needed=['ai-problem','ai-evaluation','ai-pitch'];
const formatTime=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
export default function Competition({profile,updateProfile,onAcademy}){
 const [now,setNow]=useState(Date.now()),[index,setIndex]=useState(0),[showReview,setShowReview]=useState(false);
 const state=profile?.pilot||{},run=state.run,bank=run?.kind==='diagnostic'?diagnostics:qualifiers,remaining=run?Math.max(0,Math.ceil((run.started+duration-now)/1000)):0;
 const lessonsDone=needed.filter(id=>profile?.completed?.[`academy:${id}`]).length;
 function begin(kind){updateProfile(p=>({...p,pilot:{...p.pilot,run:{kind,started:Date.now(),answers:{}},report:null}}));setIndex(0);setShowReview(false)}
 function answer(choice){updateProfile(p=>({...p,pilot:{...p.pilot,run:{...p.pilot.run,answers:{...p.pilot.run.answers,[index]:choice}}}}))}
 function finish(){if(!run)return;const result={kind:run.kind,finished:Date.now(),...score(bank,run.answers),answers:run.answers};updateProfile(p=>({...p,pilot:{...p.pilot,run:null,diagnostic:run.kind==='diagnostic'?result:p.pilot?.diagnostic,qualifier:run.kind==='qualifier'?result:p.pilot?.qualifier,report:result}}));setShowReview(false)}
 useEffect(()=>{if(!run)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[!!run]);
 useEffect(()=>{if(run&&remaining<=0)finish()},[run?.started,remaining]);
 if(!profile)return <section className="pilot"><h1>مختبر الاستعداد للمنافسة</h1><div className="glass pilot-panel"><p>افتح ملفك الشخصي من الصفحة الرئيسية أولًا حتى نحفظ نتيجة التدريب على جهازك.</p></div></section>;
 const report=state.report,reportBank=report?.kind==='diagnostic'?diagnostics:qualifiers;
 return <section className="pilot"><header><span className="eyebrow">مسار تجريبي / التطبيقات المعززة بالذكاء الاصطناعي</span><h1>من قياس المستوى إلى <em>محاكاة التصفيات</em></h1><p>أسئلة مختلفة لكل مرحلة، وتقرير مهارات يربط أخطاءك بالدرس المناسب. نتائج هذا التدريب محلية على الجهاز.</p></header>
 {!run&&!report&&<div className="pilot-steps">{[['01','اختبار المستوى','8 أسئلة · 12 دقيقة','diagnostic'],['02','التدريب الموجه','3 دروس تطبيقية: المشكلة والتقييم والعرض','learn'],['03','تصفيات تجريبية','12 سؤالًا جديدًا · 12 دقيقة','qualifier']].map(([n,title,subtitle,kind])=><article className="glass" key={n}><strong>{n}</strong><h2>{title}</h2><p>{subtitle}</p>{kind==='learn'?<button onClick={onAcademy}>اذهب إلى الدروس ←</button>:<button disabled={kind==='qualifier'&&(!state.diagnostic||lessonsDone<needed.length)} onClick={()=>begin(kind)}>{kind==='diagnostic'?'ابدأ التشخيص':state.diagnostic?lessonsDone===needed.length?'ابدأ المحاكاة':`أكمل ${needed.length-lessonsDone} دروس أولًا`:'أكمل التشخيص أولًا'} ←</button>}</article>)}</div>}
 {run&&<div className="pilot-panel glass"><div className="pilot-run-head"><span>{run.kind==='diagnostic'?'قياس المستوى':'محاكاة التصفيات'} · السؤال {index+1} من {bank.length}</span><strong aria-live="off">{formatTime(remaining)}</strong></div><div className="pilot-meter"><i style={{width:`${Object.keys(run.answers).length/bank.length*100}%`}}/></div><small>{skills[bank[index].skill].title}</small><h2>{bank[index].question}</h2><div className="pilot-choices">{bank[index].choices.map((c,i)=><button key={i} className={run.answers[index]===i?'selected':''} onClick={()=>answer(i)}>{c}</button>)}</div><div className="pilot-controls"><button disabled={index===0} onClick={()=>setIndex(index-1)}>السابق</button><button onClick={finish}>إنهاء وتسليم الإجابات</button><button disabled={index===bank.length-1} onClick={()=>setIndex(index+1)}>التالي</button></div><p>أُجب عن الأسئلة قبل انتهاء الوقت. الإجابات والتفسير يظهران بعد التسليم.</p></div>}
 {!run&&report&&<div className="glass pilot-report"><div className="pilot-report-top"><div><span className="eyebrow">تقرير {report.kind==='diagnostic'?'قياس المستوى':'محاكاة التصفيات'}</span><h2>{report.percent}% · {report.correct} من {report.total}</h2><p>{report.kind==='diagnostic'?'ابدأ بدروس المهارات التي تحتاج دعمًا ثم انتقل إلى المحاكاة.':report.percent>=80?'أداء جيد في المحاكاة؛ راجع الأخطاء قبل التدريب التالي.':'أعد تدريب المهارات الأضعف ثم حاول مجددًا.'}</p></div><strong>{report.kind==='diagnostic'?'تشخيص':'محاكاة'}</strong></div><div className="pilot-skills">{Object.entries(report.breakdown).map(([id,v])=><article key={id}><h3>{skills[id].title}</h3><span>{v.correct}/{v.total}</span><div className="pilot-meter"><i style={{width:`${v.correct/v.total*100}%`}}/></div>{v.correct<v.total&&<p>راجع درس «{skills[id].lesson==='ai-prompt'?'اكتب طلبًا واضحًا':skills[id].lesson==='ai-problem'?'من مشكلة مدرسية إلى معيار نجاح':skills[id].lesson==='ai-evaluation'?'ابنِ مجموعة اختبار عادلة':'اعرض المشروع أمام لجنة التحكيم'}».</p>}</article>)}</div><div className="pilot-report-actions"><button onClick={onAcademy}>راجع المسارات ←</button>{report.kind==='diagnostic'&&<button disabled={lessonsDone<needed.length} onClick={()=>begin('qualifier')}>{lessonsDone<needed.length?`أكمل ${needed.length-lessonsDone} دروس تأهيلية`:'ابدأ محاكاة التصفيات'}</button>}<button onClick={()=>setShowReview(!showReview)}>{showReview?'إخفاء التصحيح':'راجع الإجابات'}</button><button onClick={()=>{updateProfile(p=>({...p,pilot:{...p.pilot,report:null}}));setShowReview(false)}}>العودة للخطة</button></div>{showReview&&<div className="pilot-review">{reportBank.map((q,i)=><article key={q.id}><h3>{i+1}. {q.question}</h3><p>إجابتك: {q.choices[report.answers?.[i]]||'لم تُجب'} · {report.answers?.[i]===q.correct?'صحيحة':'تحتاج مراجعة'}</p><p>التفسير: {q.reason}</p></article>)}</div>}</div>}
 {!run&&<p className="pilot-note">هذه محاكاة تدريبية على GitHub Pages؛ الأسئلة والتصحيح موجودان في ملفات الموقع، والتوقيت والنتائج على جهاز الطالب. لا تُستخدم للترتيب الرسمي أو اختيار الفائزين.</p>}
 </section>
}
