import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {levels,questionBank,topicOrder} from './questions.js';
import './style.css';

const KEY='alzahrawi-ai-learning-v1';
const lessons=[
  {id:'python',icon:'⌘',title:'مقدمة في البرمجة بلغة بايثون',description:'المتغيرات والمدخلات وأول برنامج تفاعلي',body:'تستخدم بايثون في التعليم وتحليل البيانات والذكاء الاصطناعي. اقرأ الإدخال بواسطة input() واعرض النتائج بواسطة print().',question:'ما الدالة التي تقرأ إدخال المستخدم؟',choices:['input()','print()','len()'],correct:0},
  {id:'method',icon:'◇',title:'تطوير تطبيقات الذكاء الاصطناعي',description:'من المشكلة إلى التصميم والاختبار',body:'ابدأ بفهم المشكلة والمستخدم، ثم اجمع المتطلبات وصمم الحل ونفّذه واختبره قبل الإطلاق والصيانة.',question:'ما أول خطوة منطقية عند بناء تطبيق؟',choices:['تحديد المشكلة','نشر التطبيق','تغيير الألوان'],correct:0},
  {id:'ux',icon:'▣',title:'واجهة وتجربة المستخدم',description:'تصميم تطبيق واضح وسهل الاستخدام',body:'UI هي العناصر التي تراها، وUX هي جودة التجربة. يساعد Wireframe في ترتيب الشاشة قبل إضافة الألوان والتفاصيل.',question:'ماذا يوضح المخطط الهيكلي Wireframe؟',choices:['بنية الشاشة','كلمة المرور','سرعة الشبكة'],correct:0}
];
const emptyState={profiles:{},active:null,schoolRoster:{}};
const has=(object,key)=>Object.prototype.hasOwnProperty.call(object||{},key);
const cleanName=value=>value.trim().replace(/\s+/g,' ');
const formatTime=seconds=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;

function load(){try{const value=JSON.parse(localStorage.getItem(KEY));return value&&typeof value.profiles==='object'?{...emptyState,...value,schoolRoster:value.schoolRoster||{}}:emptyState}catch{return emptyState}}
function downloadFile(name,content,type='application/json'){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}

function LevelCards({onStart}){return <div className="level-grid">{Object.values(levels).map((level,index)=><article className={`level-card level-${level.id}`} key={level.id}><div className="level-top"><span>{level.label}</span><b>⏱ 15 دقيقة</b></div><h3>{level.title}</h3><p>{level.description}</p><div className="level-stats"><span><strong>30</strong> سؤالًا</span><span><strong>{level.pass}%</strong> للنجاح</span></div><button onClick={()=>onStart(level.id)}>بدء {index===0?'المستوى السهل':index===1?'المستوى المتوسط':'المستوى الصعب'} ←</button></article>)}</div>}

function ResultView({result,onRetry,onChoose,profile}){
  const topics=Object.entries(result.breakdown).sort((a,b)=>topicOrder.indexOf(a[0])-topicOrder.indexOf(b[0]));
  return <section className="result-wrap"><div className={`result-hero ${result.passed?'passed':'review'}`}><span className="result-icon">{result.passed?'★':'↻'}</span><div><span className="kicker">نتيجة {levels[result.level].title}</span><h2>{result.passed?'أحسنت، اجتزت المستوى!':'محاولة جيدة، واصل المراجعة'}</h2><p>{profile.name} · {profile.section||'مشارك محلي'}</p></div><div className="score-ring"><strong>{result.percent}%</strong><small>{result.score} من {result.total}</small></div></div><div className="summary-grid"><div><span>إجابات صحيحة</span><strong>{result.score}</strong></div><div><span>إجابات خاطئة</span><strong>{result.total-result.score}</strong></div><div><span>درجة النجاح</span><strong>{levels[result.level].pass}%</strong></div><div><span>النقاط المكتسبة</span><strong>+{result.pointsEarned}</strong></div></div><div className="card analysis"><h3>تحليل الأداء حسب الموضوع</h3>{topics.map(([topic,value])=>{const pct=Math.round(value.correct/value.total*100);return <div className="topic-row" key={topic}><div><b>{topic}</b><span>{value.correct}/{value.total}</span></div><div className="bar"><i style={{width:`${pct}%`}}/></div><strong>{pct}%</strong></div>})}</div><div className="result-actions"><button onClick={()=>onRetry(result.level)}>إعادة المستوى</button><button className="secondary" onClick={onChoose}>اختيار مستوى آخر</button></div></section>
}

function ExamView({profile,remaining,onAnswer,onMove,onToggleFlag,onHint,onFinish}){
  const exam=profile.exam;const questions=questionBank[exam.level];const index=exam.current||0;const question=questions[index];const answered=Object.keys(exam.answers||{}).length;const selected=exam.answers?.[index];const flagged=(exam.flagged||[]).includes(index);
  return <section className="exam-shell"><div className="exam-head card"><div><span className="kicker">{levels[exam.level].title}</span><h2>السؤال {index+1} من {questions.length}</h2></div><div className={`exam-timer ${remaining<60?'urgent':''}`}><small>الوقت المتبقي</small><strong>{formatTime(remaining)}</strong></div><button className="secondary" onClick={onHint}>✦ معلّم AI</button></div><div className="exam-layout"><article className="question-card card"><div className="question-meta"><span>{question.topic}</span><button className={flagged?'flag active':'flag'} onClick={onToggleFlag}>{flagged?'★ محدد للرجوع':'☆ تمييز للرجوع'}</button></div><h3>{index+1}. {question.question}</h3><div className="exam-choices">{question.choices.map((choice,choiceIndex)=><button className={selected===choiceIndex?'selected':''} onClick={()=>onAnswer(choiceIndex)} key={choiceIndex}><b>{String.fromCharCode(65+choiceIndex)}</b><span>{choice}</span></button>)}</div>{exam.hintFor===index&&<div className="ai-hint"><b>✦ توجيه المعلّم الذكي</b><p>{question.hint}</p><small>التلميح يوجّهك إلى الفكرة دون كشف الإجابة.</small></div>}<div className="exam-actions"><button className="secondary" disabled={index===0} onClick={()=>onMove(index-1)}>السابق</button><button className="danger-outline" onClick={()=>onFinish(false)}>إنهاء الاختبار</button><button disabled={index===questions.length-1} onClick={()=>onMove(index+1)}>التالي</button></div></article><aside className="question-map card"><h3>جدول الأسئلة</h3><p>أجبت عن {answered} من {questions.length}</p><div>{questions.map((_,i)=><button onClick={()=>onMove(i)} className={`${i===index?'current ':''}${has(exam.answers,i)?'done ':''}${(exam.flagged||[]).includes(i)?'marked':''}`} key={i}>{i+1}</button>)}</div><div className="map-key"><span><i className="done"/>مجاب</span><span><i className="marked"/>للرجوع</span></div></aside></div></section>
}

function App(){
  const [data,setData]=useState(load);const [name,setName]=useState('');const [section,setSection]=useState('');const [notice,setNotice]=useState('');const [tab,setTab]=useState('learn');const [tick,setTick]=useState(Date.now());const [roster,setRoster]=useState('');
  const profile=data.profiles[data.active];const sections=Object.keys(data.schoolRoster||{});const selectedSection=sections.includes(section)?section:sections[0];
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(data))},[data]);
  useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(timer)},[]);
  function updateProfile(fn){setData(old=>({...old,profiles:{...old.profiles,[old.active]:fn(old.profiles[old.active])}}))}
  function enter(value){const clean=cleanName(value);if(clean.length<2){setNotice('اختر اسم الطالب أولًا');return}if(sections.length&&!data.schoolRoster[selectedSection].includes(clean)){setNotice('اختر اسمًا من الشعبة المحددة');return}const id=sections.length?`${selectedSection}::${clean}`:clean.toLocaleLowerCase('ar');setData(old=>({...old,active:id,profiles:{...old.profiles,[id]:old.profiles[id]||{name:clean,section:sections.length?selectedSection:'',points:0,answered:{},attempts:[]}}}));setName('');setNotice(`مرحبًا ${clean}`)}
  function answerLesson(lesson,index){if(!profile||profile.answered?.[lesson.id])return;const correct=index===lesson.correct;updateProfile(p=>({...p,points:(p.points||0)+(correct?10:0),answered:{...(p.answered||{}),[lesson.id]:{choice:index,correct}}}));setNotice(correct?'أحسنت! حصلت على 10 نقاط':'تم تسجيل إجابتك؛ راجع الشرح واستعد للاختبارات')}
  function startExam(level){if(!profile){setNotice('اختر اسم الطالب أولًا');return}updateProfile(p=>({...p,exam:{level,started:Date.now(),answers:{},flagged:[],current:0,hintFor:null,status:'active'}}));setNotice(`بدأ ${levels[level].title} · لديك 15 دقيقة`)}
  function answerExam(choice){updateProfile(p=>({...p,exam:{...p.exam,answers:{...(p.exam.answers||{}),[p.exam.current||0]:choice}}}))}
  function moveExam(index){updateProfile(p=>({...p,exam:{...p.exam,current:index,hintFor:null}}))}
  function toggleFlag(){updateProfile(p=>{const current=p.exam.current||0;const flags=p.exam.flagged||[];return {...p,exam:{...p.exam,flagged:flags.includes(current)?flags.filter(x=>x!==current):[...flags,current]}}})}
  function showHint(){updateProfile(p=>({...p,exam:{...p.exam,hintFor:p.exam.current||0}}))}
  function finishExam(auto=false){const exam=profile?.exam;if(!exam||exam.status!=='active')return;const questions=questionBank[exam.level];const score=questions.reduce((total,item,index)=>total+(exam.answers?.[index]===item.correct?1:0),0);const percent=Math.round(score/questions.length*100);const passed=percent>=levels[exam.level].pass;const breakdown={};questions.forEach((item,index)=>{breakdown[item.topic]||={correct:0,total:0};breakdown[item.topic].total++;if(exam.answers?.[index]===item.correct)breakdown[item.topic].correct++});const pointsEarned=score*2+(passed?50:0);const result={level:exam.level,score,total:questions.length,percent,passed,breakdown,pointsEarned,finished:Date.now(),auto};updateProfile(p=>({...p,points:(p.points||0)+pointsEarned,exam:{...p.exam,status:'finished',result},attempts:[...(p.attempts||[]),result]}));setNotice(auto?'انتهى الوقت وتم حفظ النتيجة':'تم إنهاء الاختبار وحفظ النتيجة')}
  const remaining=useMemo(()=>{if(!profile?.exam||profile.exam.status!=='active')return 0;const duration=levels[profile.exam.level].duration;return Math.max(0,Math.ceil((profile.exam.started+duration*1000-tick)/1000))},[profile?.exam,tick]);
  useEffect(()=>{if(profile?.exam?.status==='active'&&remaining===0)finishExam(true)},[remaining]);
  function backup(){downloadFile('ai-learning-local-backup.json',JSON.stringify(data,null,2))}
  function exportResults(){const rows=[['الطالب','الشعبة','المستوى','الدرجة','الإجمالي','النسبة','الحالة','التاريخ']];Object.values(data.profiles).forEach(p=>(p.attempts||[]).forEach(r=>rows.push([p.name,p.section||'',levels[r.level]?.title||r.level,r.score,r.total,`${r.percent}%`,r.passed?'ناجح':'يحتاج مراجعة',new Date(r.finished).toLocaleString('ar-OM')])));if(rows.length===1){setNotice('لا توجد نتائج اختبارات لتصديرها');return}const csv='\uFEFF'+rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n');downloadFile('نتائج-منصة-التعلم.csv',csv,'text/csv;charset=utf-8')}
  async function restore(e){const file=e.target.files?.[0];if(!file)return;try{const value=JSON.parse(await file.text());if(!value||typeof value.profiles!=='object')throw Error();setData({...emptyState,...value,active:null});setNotice('استُعيدت البيانات المحلية بنجاح')}catch{setNotice('ملف النسخة الاحتياطية غير صالح')}e.target.value=''}
  function addRoster(){const names=roster.split(/[\n,،]+/).map(cleanName).filter(x=>x.length>=2);setData(old=>({...old,schoolRoster:{...old.schoolRoster,'إضافي':[...new Set([...(old.schoolRoster?.['إضافي']||[]),...names])]}}));setRoster('');setNotice(`أُضيف ${names.length} اسمًا إلى قسم «إضافي»`)}
  async function importSchoolRoster(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>2_000_000)throw Error('الملف أكبر من الحد المسموح');const value=JSON.parse(await file.text());if(!value||Array.isArray(value)||typeof value!=='object')throw Error('صيغة الملف غير صحيحة');const result={};for(const [className,list] of Object.entries(value)){if(!className.trim()||!Array.isArray(list)||!list.every(n=>typeof n==='string'))throw Error('صيغة الشعب أو الأسماء غير صحيحة');result[className.trim()]=[...new Set(list.map(cleanName).filter(n=>n.length>=2))]}if(!Object.keys(result).length)throw Error('الملف لا يحتوي على شعب');setData(old=>({...old,schoolRoster:result,active:null}));setSection(Object.keys(result)[0]);setName('');setNotice(`تم استيراد ${Object.values(result).reduce((n,a)=>n+a.length,0)} اسمًا في ${Object.keys(result).length} شعبة`)}catch(error){setNotice(error.message||'تعذر قراءة ملف الطلاب')}e.target.value=''}
  const rankings=Object.values(data.profiles).sort((a,b)=>(b.points||0)-(a.points||0)||a.name.localeCompare(b.name,'ar'));const totalAttempts=Object.values(data.profiles).reduce((sum,p)=>sum+(p.attempts?.length||0),0);
  return <div className="app" dir="rtl"><header><div className="brand"><span className="logo">✦</span><span>منصة التعلم والمسابقات<small>مدرسة أبو القاسم الزهراوي للتعليم الأساسي</small></span></div><span className="badge">نسخة GitHub · تعمل دون خادم</span></header><main><section className="hero"><span className="eyebrow">تعلّم · طبّق · تنافس</span><h1>رحلتك في البرمجة<br/>تبدأ من هنا.</h1><p>مسارات تعليمية وثلاثة اختبارات متدرجة مع معلّم ذكي وتحليل فوري لمستواك.</p><div className="hero-pills"><span>90 سؤالًا</span><span>3 مستويات</span><span>تحليل فوري</span></div></section><div className="privacy">تُحفظ الأسماء والنتائج على هذا الجهاز فقط. لا يُرفع ملف الطلاب إلى GitHub ولا تنتقل النتائج تلقائيًا بين الأجهزة.</div>{notice&&<div className="notice" role="status" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}
  <section className="profile card"><div><span className="kicker">ملفك المحلي</span><h2>{profile?`أهلًا، ${profile.name}`:'اختر اسمك للبدء'}</h2><p>{profile?`${profile.section?profile.section+' · ':''}رصيدك: ${profile.points||0} نقطة · المحاولات: ${profile.attempts?.length||0}`:'استورد ملف الطلاب في «إدارة الجهاز» أو اكتب اسمًا تجريبيًا.'}</p></div><div className="profile-actions">{profile&&<button className="secondary" onClick={()=>setData(old=>({...old,active:null}))}>تبديل الطالب</button>}{!profile&&<>{sections.length?<><select aria-label="الشعبة" value={selectedSection} onChange={e=>{setSection(e.target.value);setName('')}}>{sections.map(s=><option value={s} key={s}>{s}</option>)}</select><select aria-label="اسم الطالب" value={name} onChange={e=>setName(e.target.value)}><option value="">اختر الطالب</option>{data.schoolRoster[selectedSection]?.map(n=><option value={n} key={n}>{n}</option>)}</select></>:<input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&enter(name)} placeholder="اسم تجريبي" aria-label="اسم الطالب"/>}<button onClick={()=>enter(name)}>ابدأ التعلم</button></>}</div></section>
  <nav className="tabs" aria-label="أقسام المنصة"><button className={tab==='learn'?'active':''} onClick={()=>setTab('learn')}>المسارات التعليمية</button><button className={tab==='competition'?'active':''} onClick={()=>setTab('competition')}>الاختبارات الذكية</button><button className={tab==='board'?'active':''} onClick={()=>setTab('board')}>لوحة الشرف</button><button className={tab==='manage'?'active':''} onClick={()=>setTab('manage')}>إدارة الجهاز</button></nav>
  {tab==='learn'&&<div className="cards">{lessons.map((lesson,index)=><article className="card lesson" key={lesson.id}><div className="lesson-head"><span className="icon">{lesson.icon}</span><span className="count">المسار {String(index+1).padStart(2,'0')}</span></div><h2>{lesson.title}</h2><p>{lesson.description}</p><details><summary>افتح الدرس والسؤال</summary><div className="lesson-body"><p>{lesson.body}</p><strong>{lesson.question}</strong><div className="choices">{lesson.choices.map((choice,choiceIndex)=><button key={choiceIndex} disabled={!profile||!!profile.answered?.[lesson.id]} onClick={()=>answerLesson(lesson,choiceIndex)}>{choice}</button>)}</div>{profile?.answered?.[lesson.id]&&<p className="answer">{profile.answered[lesson.id].correct?'إجابة صحيحة ✓':'الإجابة الصحيحة: '+lesson.choices[lesson.correct]}</p>}</div></details></article>)}</div>}
  {tab==='competition'&&<>{!profile?<section className="card feature"><h2>اختر اسم الطالب أولًا</h2><p>بعد اختيار الاسم ستظهر المستويات الثلاثة ويُحفظ تقدم الطالب على هذا الجهاز.</p></section>:profile.exam?.status==='active'?<ExamView profile={profile} remaining={remaining} onAnswer={answerExam} onMove={moveExam} onToggleFlag={toggleFlag} onHint={showHint} onFinish={finishExam}/>:profile.exam?.status==='finished'?<ResultView result={profile.exam.result} profile={profile} onRetry={startExam} onChoose={()=>updateProfile(p=>({...p,exam:null}))}/>:<section><div className="section-heading"><span className="kicker">اختبارات معتمدة على محاور التدريب</span><h2>اختر مستواك وابدأ التحدي</h2><p>لكل مستوى 30 سؤالًا و15 دقيقة. يمكنك الاستعانة بتلميح المعلّم الذكي وتحديد الأسئلة للرجوع إليها.</p></div><LevelCards onStart={startExam}/></section>}</>}
  {tab==='board'&&<section className="card feature board"><div className="board-head"><div><span className="kicker">النتائج المحلية</span><h2>لوحة الشرف على هذا الجهاز</h2></div><span>{totalAttempts} محاولة اختبار</span></div>{rankings.length?rankings.map((p,index)=><div className="rank" key={`${p.section||''}:${p.name}`}><span><b>{String(index+1).padStart(2,'0')}</b>{p.name}{p.section&&<small> · {p.section}</small>}</span><strong>{p.points||0} نقطة</strong></div>):<p>لا توجد مشاركات بعد.</p>}</section>}
  {tab==='manage'&&<section className="card feature"><span className="kicker">إعداد الجهاز</span><h2>استيراد بيانات الطلاب والنتائج</h2><p>اختر ملف <code>studentData.json</code>. ستظهر الشعب والأسماء للاختيار محليًا ولن يُرسل الملف إلى GitHub.</p><div className="actions"><label className="upload">اختر ملف الطلاب<input type="file" accept="application/json,.json" onChange={importSchoolRoster}/></label></div>{sections.length>0&&<p className="answer">تم تجهيز {Object.values(data.schoolRoster).reduce((n,a)=>n+a.length,0)} اسمًا في {sections.length} شعبة.</p>}<h3>إضافة أسماء يدويًا</h3><textarea rows="4" value={roster} onChange={e=>setRoster(e.target.value)} placeholder={'اسم الطالب الأول\nاسم الطالب الثاني'}/><div className="actions"><button onClick={addRoster} disabled={!roster.trim()}>أضف الأسماء</button><button className="secondary" onClick={exportResults}>تصدير النتائج Excel/CSV</button><button className="secondary" onClick={backup}>تنزيل نسخة احتياطية</button><label className="upload">استيراد نسخة احتياطية<input type="file" accept="application/json,.json" onChange={restore}/></label></div><p className="muted">النسخة الاحتياطية تحتوي الأسماء والنتائج. احتفظ بها في مكان آمن، لأن استيرادها يستبدل البيانات المحلية على هذا الجهاز.</p></section>}
  </main><footer>الأستاذ أحمد الضامري · منصة تدريبية محلية النتائج</footer></div>
}

createRoot(document.getElementById('root')).render(<App/>);
