import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const KEY='alzahrawi-ai-learning-v1';
const lessons=[
  {id:'python',icon:'⌘',title:'مقدمة في البرمجة بلغة البايثون',description:'المتغيرات والمدخلات وأول برنامج تفاعلي',body:'لغة بايثون مناسبة للمبتدئين. استخدم input() لقراءة إجابة المستخدم، وprint() لعرض رسالة له.',question:'ما الدالة التي تقرأ إدخال المستخدم؟',choices:['input()','print()','len()'],correct:0},
  {id:'method',icon:'◇',title:'منهجيات تطوير تطبيقات الذكاء الاصطناعي',description:'من المشكلة إلى التصميم والاختبار',body:'ابدأ بتحديد المشكلة واحتياجات المستخدم، ثم صمم الحل واختبره قبل نشره.',question:'ما أول خطوة عند بناء تطبيق؟',choices:['تحديد المشكلة','نشر التطبيق','تغيير الألوان'],correct:0},
  {id:'ux',icon:'▣',title:'واجهة وتجربة المستخدم',description:'تصميم تطبيق واضح وسهل الاستخدام',body:'واجهة المستخدم هي ما تراه على الشاشة. تجربة المستخدم هي مدى سهولة الوصول إلى هدفك. يساعد المخطط الهيكلي في ترتيب عناصر الشاشة قبل تصميمها.',question:'ماذا يوضح المخطط الهيكلي Wireframe؟',choices:['بنية الشاشة','كلمة المرور','سرعة الشبكة'],correct:0}
];
const newState={profiles:{},active:null};
function load(){try{const value=JSON.parse(localStorage.getItem(KEY));return value&&typeof value.profiles==='object'?value:newState}catch{return newState}}
function App(){const[data,setData]=useState(load);const[name,setName]=useState('');const[notice,setNotice]=useState('');const[tab,setTab]=useState('learn');const[tick,setTick]=useState(Date.now());const[roster,setRoster]=useState('');
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(data))},[data]);
  useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(timer)},[]);
  const profile=data.profiles[data.active];
  function updateProfile(fn){setData(old=>({...old,profiles:{...old.profiles,[old.active]:fn(old.profiles[old.active])}}))}
  function enter(value){const clean=value.trim().replace(/\s+/g,' ');if(clean.length<2){setNotice('اكتب اسمًا من حرفين على الأقل');return}const id=clean.toLocaleLowerCase('ar');setData(old=>({...old,active:id,profiles:{...old.profiles,[id]:old.profiles[id]||{name:clean,points:0,answered:{},competition:null}}}));setName('');setNotice('مرحبًا '+clean)}
  function answerLesson(lesson,index){if(!profile||profile.answered[lesson.id])return;const correct=index===lesson.correct;updateProfile(p=>({...p,points:p.points+(correct?10:0),answered:{...p.answered,[lesson.id]:{choice:index,correct}}}));setNotice(correct?'أحسنت! حصلت على ١٠ نقاط':'تم تسجيل إجابتك؛ تابع التعلم وحاول في المسابقة')}
  function startCompetition(){if(!profile)return;updateProfile(p=>({...p,competition:{started:Date.now(),answers:{}}}));setNotice('بدأ تحديك المحلي: لديك ٣ دقائق')}
  function answerCompetition(lesson,index){const game=profile?.competition;if(!game||game.answers[lesson.id]||tick-game.started>=180000)return;const correct=index===lesson.correct;updateProfile(p=>({...p,points:p.points+(correct?20:0),competition:{...p.competition,answers:{...game.answers,[lesson.id]:{choice:index,correct}}}}));setNotice(correct?'إجابة صحيحة! ٢٠ نقطة':'سُجّلت الإجابة')}
  function backup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ai-learning-local-backup.json';a.click();URL.revokeObjectURL(url)}
  async function restore(e){const file=e.target.files?.[0];if(!file)return;try{const value=JSON.parse(await file.text());if(!value||typeof value.profiles!=='object')throw Error();setData({...value,active:null});setNotice('استُعيدت البيانات المحلية بنجاح')}catch{setNotice('ملف النسخة الاحتياطية غير صالح')}e.target.value=''}
  function addRoster(){const names=roster.split(/[\n,،]+/).map(x=>x.trim().replace(/\s+/g,' ')).filter(x=>x.length>=2);setData(old=>{const profiles={...old.profiles};names.forEach(n=>{const id=n.toLocaleLowerCase('ar');profiles[id]??={name:n,points:0,answered:{},competition:null}});return {...old,profiles}});setRoster('');setNotice(`أُضيف ${names.length} اسمًا على هذا الجهاز`)}
  const remaining=profile?.competition?Math.max(0,Math.min(180,Math.ceil((180000-(tick-profile.competition.started))/1000))):180;
  const rankings=Object.values(data.profiles).sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name,'ar'));
  return <div className="app"><header><div className="brand"><span className="logo">✦</span><span>منصة التعلم والمسابقات<small>مدرسة أبو القاسم الزهراوي للتعليم الأساسي</small></span></div><span className="badge">نسخة GitHub · تعمل دون خادم</span></header><main><section className="hero"><span className="eyebrow">تعلّم · طبّق · تنافس</span><h1>رحلتك في البرمجة<br/>تبدأ من هنا.</h1><p>ثلاثة مسارات قصيرة وتحدٍ موقوت يساعدك على قياس تقدمك.</p></section><div className="privacy">تُحفظ الأسماء والنقاط على هذا الجهاز فقط. اختيار الاسم ليس تسجيل دخول آمنًا، ولا تنتقل النتائج تلقائيًا بين الأجهزة.</div>{notice&&<div className="notice" role="status" onClick={()=>setNotice('')}>{notice} <span>×</span></div>}
<section className="profile card"><div><span className="kicker">ملفك المحلي</span><h2>{profile?`أهلًا، ${profile.name}`:'اختر اسمك للبدء'}</h2><p>{profile?`رصيدك الحالي: ${profile.points} نقاط`:'يمكنك إضافة أسماء الطلاب أولًا في قسم إدارة الأسماء المحلية.'}</p></div><div className="profile-actions">{profile&&<button className="secondary" onClick={()=>setData(old=>({...old,active:null}))}>تبديل الطالب</button>}{!profile&&<><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&enter(name)} list="names" placeholder="اكتب اسم الطالب" aria-label="اسم الطالب"/><datalist id="names">{rankings.map(p=><option value={p.name} key={p.name}/>)}</datalist><button onClick={()=>enter(name)}>ابدأ التعلم</button></>}</div></section>
<nav className="tabs" aria-label="أقسام المنصة"><button className={tab==='learn'?'active':''} onClick={()=>setTab('learn')}>المسارات التعليمية</button><button className={tab==='competition'?'active':''} onClick={()=>setTab('competition')}>التحدي المحلي</button><button className={tab==='board'?'active':''} onClick={()=>setTab('board')}>لوحة الشرف</button><button className={tab==='manage'?'active':''} onClick={()=>setTab('manage')}>إدارة الجهاز</button></nav>
{tab==='learn'&&<div className="cards">{lessons.map((l,i)=><article className="card lesson" key={l.id}><div className="lesson-head"><span className="icon">{l.icon}</span><span className="count">المسار {String(i+1).padStart(2,'0')}</span></div><h2>{l.title}</h2><p>{l.description}</p><details><summary>افتح الدرس والسؤال</summary><div className="lesson-body"><p>{l.body}</p><strong>{l.question}</strong><div className="choices">{l.choices.map((c,j)=><button key={j} disabled={!profile||!!profile.answered[l.id]} onClick={()=>answerLesson(l,j)}>{c}</button>)}</div>{profile?.answered[l.id]&&<p className="answer">{profile.answered[l.id].correct?'إجابة صحيحة ✓':'الإجابة الصحيحة: '+l.choices[l.correct]}</p>}</div></details></article>)}</div>}
{tab==='competition'&&<section className="card feature"><span className="kicker">مسابقة على هذا الجهاز</span><h2>تحدي المعرفة · ٣ دقائق</h2><p>ثلاثة أسئلة من الدروس. يبدأ التوقيت لكل طالب عند ضغط «ابدأ التحدي»، وتُحفظ نتيجته في هذا المتصفح.</p>{!profile?<p>اختر اسمك أولًا.</p>:!profile.competition?<button onClick={startCompetition}>ابدأ التحدي</button>:<><div className="timer">{remaining?`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`:'انتهى الوقت'}</div>{remaining>0?lessons.map((l,i)=><div className="challenge" key={l.id}><h3>{i+1}. {l.question}</h3><div className="choices">{l.choices.map((choice,j)=><button disabled={!!profile.competition.answers[l.id]} onClick={()=>answerCompetition(l,j)} key={j}>{choice}</button>)}</div>{profile.competition.answers[l.id]&&<span className="answer">{profile.competition.answers[l.id].correct?'إجابة صحيحة ✓':'سُجّلت الإجابة'}</span>}</div>):<p>انتهى التحدي. يمكنك متابعة التعلم وعرض ترتيبك في لوحة الشرف.</p>}</>}</section>}
{tab==='board'&&<section className="card feature"><span className="kicker">النتائج المحلية</span><h2>لوحة الشرف على هذا الجهاز</h2>{rankings.length?rankings.map((p,i)=><div className="rank" key={p.name}><span><b>{String(i+1).padStart(2,'0')}</b> {p.name}</span><strong>{p.points} نقطة</strong></div>):<p>لا توجد أسماء بعد.</p>}</section>}
{tab==='manage'&&<section className="card feature"><span className="kicker">إعداد بسيط</span><h2>إدارة الأسماء والنسخ الاحتياطية</h2><p>ألصق أسماء الطلاب، كل اسم في سطر. تبقى الأسماء على هذا الجهاز ولا تُرفع إلى GitHub.</p><textarea rows="6" value={roster} onChange={e=>setRoster(e.target.value)} placeholder="اسم الطالب الأول&#10;اسم الطالب الثاني"/><div className="actions"><button onClick={addRoster} disabled={!roster.trim()}>أضف الأسماء</button><button className="secondary" onClick={backup}>تنزيل نسخة احتياطية</button><label className="upload">استيراد نسخة احتياطية<input type="file" accept="application/json,.json" onChange={restore}/></label></div><p className="muted">النسخة الاحتياطية تحتوي الأسماء والنتائج؛ احتفظ بها في مكان آمن. الاستيراد يستبدل البيانات المحلية على هذا الجهاز.</p></section>}
</main><footer>الأستاذ أحمد الضامري · منصة تدريبية محلية النتائج</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
