import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
function App(){const[token,setToken]=useState(sessionStorage.getItem('token')||'');const[profile,setProfile]=useState(null);const[courses,setCourses]=useState([]);const[board,setBoard]=useState([]);const[comps,setComps]=useState([]);const[live,setLive]=useState(null);const[questions,setQuestions]=useState([]);const[form,setForm]=useState({username:'',password:'',display_name:''});const[signup,setSignup]=useState(false);const[msg,setMsg]=useState('');
async function request(path,options={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'تعذر إكمال الطلب');return data}
async function refresh(){try{const [a,b,c]=await Promise.all([request('/courses'),request('/leaderboard'),request('/competitions')]);setCourses(a);setBoard(b);setComps(c);if(token)setProfile(await request('/me'))}catch(e){setMsg(e.message)}}
useEffect(()=>{refresh()},[token]);
useEffect(()=>{if(!token||!live)return;const ws=new WebSocket(API.replace(/^http/,'ws')+`/ws/competitions/${live}?token=${encodeURIComponent(token)}`);ws.onmessage=e=>{const state=JSON.parse(e.data);setComps(old=>old.map(c=>c.id===live?{...c,...state}:c));if(state.status==='closed')setQuestions([])};return()=>ws.close()},[live,token]);
async function auth(e){e.preventDefault();try{if(signup){await request('/auth/register',{method:'POST',body:JSON.stringify(form)});setSignup(false);setMsg('تم إنشاء الحساب؛ سجّل الدخول الآن')}else{const d=await request('/auth/login',{method:'POST',body:JSON.stringify(form)});sessionStorage.setItem('token',d.access_token);setToken(d.access_token);setMsg('أهلًا بك')}}catch(x){setMsg(x.message)}}
async function submit(path,question_id,answer_index){try{const d=await request(path,{method:'POST',body:JSON.stringify({question_id,answer_index})});setMsg(d.correct?`إجابة صحيحة! +${d.awarded} نقطة`:'إجابة غير صحيحة');refresh()}catch(x){setMsg(x.message)}}
async function enter(id){setLive(id);try{setQuestions(await request(`/competitions/${id}/questions`))}catch(x){setQuestions([]);setMsg(x.message)}}
return <div className="app"><header><div className="brand">✦ منصة التعلم والمسابقات <small>مدرسة أبو القاسم الزهراوي</small></div>{profile?<div className="user">{profile.display_name} · {profile.points} نقطة <button onClick={()=>{sessionStorage.removeItem('token');setToken('');setProfile(null);setLive(null)}}>خروج</button></div>:<span>تعلم · تدرب · تنافس</span>}</header><main><section className="hero"><span className="tag">تعلّم بخطوات واضحة</span><h1>ابدأ رحلتك في البرمجة والذكاء الاصطناعي</h1><p>دروس قصيرة، أسئلة تفاعلية، ومسابقات مباشرة في وقت محدد.</p></section>{msg&&<p role="status" className="notice" onClick={()=>setMsg('')}>{msg} ×</p>}{!token&&<section className="card auth"><h2>{signup?'إنشاء حساب طالب':'دخول الطالب'}</h2><form onSubmit={auth}>{signup&&<input required placeholder="الاسم الظاهر" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/>}<input required minLength="3" placeholder="اسم المستخدم" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input required minLength="8" type="password" placeholder="كلمة المرور (٨ أحرف على الأقل)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button>{signup?'سجّل':'دخول'}</button></form><button className="link" onClick={()=>setSignup(!signup)}>{signup?'لديك حساب؟ دخول':'أنشئ حسابًا جديدًا'}</button></section>}<div className="grid"><section><h2>المسارات التعليمية</h2>{courses.map(c=><article className="card" key={c.id}><h3>{c.title}</h3><p>{c.description}</p>{c.lessons.map(l=><details key={l.id}><summary>{l.title}</summary><p>{l.content}</p>{l.questions.map(q=><div key={q.id}><b>{q.text}</b><div className="choices">{q.choices.map((choice,i)=><button disabled={!token} key={i} onClick={()=>submit(`/lessons/${l.id}/answers`,q.id,i)}>{choice}</button>)}</div></div>)}</details>)}</article>)}</section><aside><section className="card"><h2>المسابقات المباشرة</h2>{comps.length===0?<p>لا توجد مسابقات مجدولة بعد.</p>:comps.map(c=><div className="comp" key={c.id}><b>{c.title}</b><small>{new Date(c.starts_at).toLocaleString('ar-OM')} · {c.status==='open'?'مفتوحة':c.status==='closed'?'انتهت':'قريبًا'}</small>{token&&<button onClick={()=>enter(c.id)}>دخول الغرفة</button>}{live===c.id&&<><p>{c.status==='open'?`المتبقي ${c.seconds_remaining??'…'} ثانية`:c.status==='upcoming'?'تفتح قريبًا':'انتهت المسابقة'}</p>{questions.map(q=><div key={q.id}><b>{q.text}</b><div className="choices">{q.choices.map((v,i)=><button key={i} onClick={()=>submit(`/competitions/${c.id}/answers`,q.id,i)}>{v}</button>)}</div></div>)}{c.leaderboard?.map((r,i)=><p key={i}>{i+1}. {r.name} · {r.points}</p>)}</>}</div>)}</section><section className="card"><h2>لوحة الشرف</h2>{board.length?board.map((r,i)=><div className="rank" key={i}><span>{i+1}. {r.name}</span><b>{r.points}</b></div>):<p>كن أول من يكسب النقاط!</p>}</section></aside></div></main><footer>منصة تعليمية تجريبية · الأستاذ أحمد الضامري</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
